### ISSUE TITLE
Cannot move the temp file

### ISSUE THREAD

**Issue by phantom153** [Belval/pdf2image#61] opened 2019-04-20 18:46 UTC
Hi,
I am using convert_from_path:
 pages = convert_from_path(filename, dpi=200, output_folder = inputPath + "\\temp", fmt='jpg', last_page=1, first_page =0, thread_count=1)
After this is executed I am copying the file to a standard filename:
file2=os.listdir(inputPath+"\\temp")[0]
JPGfilename = os.path.join(inputPath+"\\temp", file2)                                        shutil.move(JPGfilename, inputPath +'\\temp.jpg')

However SHUTIL cannot move the file because of permission error.

How can I close the process that is still using the temp file convert_from_path created?

Thanks!

**Comment by Belval** [comment] 2019-04-20 20:08
I was not able to reproduce your problem on Ubuntu 18.04 using a test PDF. Here's my code:

```py
import os
import shutil

from pdf2image import convert_from_path

def main():
    pages = convert_from_path('./test.pdf', dpi=200, output_folder="./temp", fmt='jpg', last_page=1, first_page=0, thread_count=1)

    file2 = os.listdir('./temp')[0]
    jpgfile = os.path.join('./temp/', file2)
    shutil.move(jpgfile, './temp.jpg')

if __name__=='__main__':
    main()
```

It assumes that `./temp` exists. 

I am willing to assist you with this but I will need more info on your setup.

**Comment by phantom153** [comment] 2019-04-21 06:18
Dear Edouard,

Thank you for your quick reply and your willingness to help!
I am using windows.
There is some procedure I might need to close. Any ideas?
BTW – I need to use the temp directory because with PDF files larger than 15Mbs the process halts.

Best Regards,

Gil

**Comment by phantom153** [comment] 2019-04-21 06:20
This is the error:
shutil.move(JPGfilename, inputPath +'\\temp.jpg')"): [WinError 32] The process cannot access the file because it is being used by another process

From: Dr. Gil Tomer
Sent: יום א 21 אפריל 2019 09:18
To: Belval/pdf2image <reply@reply.github.com>; Belval/pdf2image <pdf2image@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Belval/pdf2image] Cannot move the temp file (#61)

Dear Edouard,

Thank you for your quick reply and your willingness to help!
I am using windows.
There is some procedure I might need to close. Any ideas?
BTW – I need to use the temp directory because with PDF files larger than 15Mbs the process halts.

Best Regards,

Gil

**Comment by phantom153** [comment] 2019-04-21 14:03
Hi,

Problem solved(!!) with a simple:
pages[0].close()

Thanks and Happy Easter,

Gil

From: Dr. Gil Tomer
Sent: יום א 21 אפריל 2019 09:21
To: Belval/pdf2image <reply@reply.github.com>; Belval/pdf2image <pdf2image@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Belval/pdf2image] Cannot move the temp file (#61)

This is the error:
shutil.move(JPGfilename, inputPath +'\\temp.jpg')"): [WinError 32] The process cannot access the file because it is being used by another process

From: Dr. Gil Tomer
Sent: יום א 21 אפריל 2019 09:18
To: Belval/pdf2image <reply@reply.github.com<mailto:reply@reply.github.com>>; Belval/pdf2image <pdf2image@noreply.github.com<mailto:pdf2image@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [Belval/pdf2image] Cannot move the temp file (#61)

Dear Edouard,

Thank you for your quick reply and your willingness to help!
I am using windows.
There is some procedure I might need to close. Any ideas?
BTW – I need to use the temp directory because with PDF files larger than 15Mbs the process halts.

Best Regards,

Gil

**Comment by Belval** [comment] 2019-04-21 14:33
Oh my bad, can't believe that I didn't think about that.

**Comment by Rim13** [comment] 2019-04-22 16:00
Have the same error " PermissionError: [WinError 32] "
Windows 10 Python 3.7 pdf2image 1.5.1

`import os
import tempfile
from pdf2image import convert_from_path

filename = 'target.pdf'
save_dir = 'C:\\1'
 
with tempfile.TemporaryDirectory() as path:
    images_from_path = convert_from_path(filename, output_folder=path, last_page=1, first_page =0)
 
base_filename  =  os.path.splitext(os.path.basename(filename))[0] + '.jpg'     
 
for page in images_from_path:
    page.save(os.path.join(save_dir, base_filename), 'JPEG')`

Where should I insert this thing in this code " .close() "?

**Comment by phantom153** [comment] 2019-04-22 16:04
Add:
images_from_path[0].close()
before trying to access or delete the file

**Comment by Belval** [comment] 2019-04-28 00:09
Closing, as I think the issue was solved. Feel free to reopen if you don't.

**Closed by Belval** 2019-04-28 00:09 UTC
Labels: need more info
