### ISSUE TITLE
Use Utf-8 to convert pdf to image 

### ISSUE THREAD

**Issue by ferdinandhuang** [Belval/pdf2image#43] opened 2018-12-29 07:21 UTC
When I try to convert an invoice pdf to image, i use the sample code to convert it.
But I got an invoice framework with number and characters and without all the Chinese text.
I want to use utf-8 encode with the pdf text, and I can't find any way to do that.
Is there any solutions?
Thanks so much

**Comment by Belval** [comment] 2018-12-29 15:05
Are you using Python 2 or Python 3?

**Comment by Belval** [comment] 2019-01-02 12:10
Hmm then I don't really know, pdftoppm/pdftocairo don't have encoding options so it's probably the system configuration that is problematic.

Do you have a pdf I could convert on my side to reproduce the issue?

**Comment by ferdinandhuang** [comment] 2019-01-03 01:32
> Hmm then I don't really know, pdftoppm/pdftocairo don't have encoding options so it's probably the system configuration that is problematic.
> 
> Do you have a pdf I could convert on my side to reproduce the issue?

[051001800211-19368739.pdf](https://github.com/Belval/pdf2image/files/2722557/051001800211-19368739.pdf)

That's my test pdf.

**Comment by Belval** [comment] 2019-01-08 01:09
This is what I get when I convert your document on my computer. Is this the expected behavior?

If not, what is wrong with the following image?

![test](https://user-images.githubusercontent.com/5399488/50803486-0cd3cb80-12b8-11e9-8a04-876ff4aac4eb.jpg)

**Comment by ferdinandhuang** [comment] 2019-01-08 01:46
> This is what I get when I convert your document on my computer. Is this the expected behavior?
> 
> If not, what is wrong with the following image?
> 
> ![test](https://user-images.githubusercontent.com/5399488/50803486-0cd3cb80-12b8-11e9-8a04-876ff4aac4eb.jpg)

Yes! That's my expect, but i got image which use the demo code like this:
![image](https://user-images.githubusercontent.com/11863965/50804694-29105080-132a-11e9-9571-39ca848332cb.png)

**Comment by Belval** [comment] 2019-01-08 13:39
What is your operating system?

I am pretty sure that the problem is not pdf2image.

**Comment by ferdinandhuang** [comment] 2019-01-09 01:34
Operation system is Windows 10, and my code is just like this:
`images = convert_from_path('D:/Code/Demo/PyDemo/sample1.pdf')`
`c = 1`
`for image in images:`
`    image.save('D:/Code/Demo/PyDemo/out/out' + str(c) + '.jpg', 'JPEG')`
`    c = c + 1`

**Comment by chenxu7601257** [comment] 2019-01-09 02:03
@Belval Thanks for your time. I got the same issue as ferdinandhuang mentioned above, the image is there but the chars especially the Chinese chars are all missing. Would it be possible to share your findings? Much appreciated.

**Comment by Belval** [comment] 2019-01-09 03:39
That's the thing, I did nothing. I don't have any rendering problem on both my Ubuntu 18.04 and archlinux machines when converting this PDF using pdf2image...

Does it show correctly when you open it in a browser?

**Comment by ferdinandhuang** [comment] 2019-01-09 08:05
Thanks for you reply.
I tried in Ubuntu, it work correct as I expect. So I think maybe this problem is poppler for Windows's problem.
At last, thank you again.

**Comment by Belval** [comment] 2019-01-15 16:03
Closing as this is probably not a `pdf2image` issue. Feel free to reopen if you gather additional information.

**Closed by Belval** 2019-01-15 16:03 UTC

**Comment by ryul99** [comment] 2020-06-03 08:19
@Belval I had the same Issue in ubuntu docker. (table and image is saved but the text is not saved)
I solved this by `apt-get install poppler-data`. I think this occurs when poppler doesn't font.

**Comment by Belval** [comment] 2020-06-03 18:34
Interesting, I'll see if I can add a test to detect that.
