### ISSUE TITLE
Unable to convert PDF to TIFF using the present pdf2Image code base in the github.

### ISSUE THREAD

**Issue by yogi2806** [Belval/pdf2image#173] opened 2020-11-06 11:32 UTC
**Describe the bug**
Unable to convert PDF to TIFF using the present pdf2Image code base in the github. I tried running **test_conversion_to_tiff_from_path_using_dir** method from test.py which doesnt generate TIF file. 
This is how I call the tiff method:
**images_from_path = convert_from_path(
                "./tests/test.pdf", output_folder="./output/", fmt="tiff",poppler_path="D:/xx/poppler-20.11.0/bin"
            )**

**To Reproduce**
1.Opened test.py
2. Ran test_conversion_to_tiff_from_path_using_dir function
3. i get below error:
**"cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file './output/test-1.tif'**

**Expected behavior**
Tiff file should be generated from sample test.pdf file. But i was able to generate png,jpeg files.

**Desktop (please complete the following information):**
 - OS: Windows 10

i also directly tried to use this command: **pdftocairo.exe test.pdf -tiff** which also generates same output like test.tif file with 0kb.

Kindly help me out to fix this.

**Comment by Belval** [comment] 2020-11-07 05:28
This is a somewhat known issue. libtiff is not supported by the version of poppler available through the poppler-windows repository. The parameter works on Mac/Linux. I, unfortunately, haven't had the time to fix it myself. See: https://github.com/oschwartz10612/poppler-windows/issues/5

**Comment by yogi2806** [comment] 2020-11-09 04:32
Any ETA for this issue ? 

I have raised same issue in poppler's forum if you could follow-up or get some sort of solution from them:
**https://gitlab.freedesktop.org/poppler/poppler/-/issues/985**

**Comment by Belval** [comment] 2021-02-06 21:40
This is not a bug in `pdf2image` and as such I will close the issue. This is related to how the poppler library is built for windows and was addressed by a recent version of poppler-windows. See: https://github.com/oschwartz10612/poppler-windows/issues/5

**Closed by Belval** 2021-02-06 21:40 UTC
Labels: not a bug
