### ISSUE TITLE
pdf2image outputs 1x1 blank image

### ISSUE THREAD

**Issue by dougsouza** [Belval/pdf2image#34] opened 2018-11-20 15:02 UTC
**Describe the bug**
For some pdf files, `convert_from_path, convert_from_bytes` outputs a blank 1x1 PIL image. Interestingly for very similar pdfs it works fine. The documents are mostly one very long page pdfs. Any ideais?

**To Reproduce**
1. Unfortunately the pdfs I'm working on are confidential and I am not allowed to share

**Expected behavior**
I would expect to see a normal PIL image, as happened to other similar pdfs.

**Screenshots**
Output: `[<PIL.PpmImagePlugin.PpmImageFile image mode=RGB size=1x1 at 0x7FCC6C3FA4A8>]`. The number of pages is correct, the pdf is just one very long page.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Comment by Belval** [comment] 2018-11-20 17:09
As pdf2image is only a thin wrapper around pdftoppm, I would try directly from the CLI.

Something like `pdftoppm -r 200 -jpeg your_pdf.pdf out.jpg`

If you still get a 1x1 pixel then the problem is on their side and I can't help much.

It would also help if you could provide the exact call you do on `convert_from_path`/`convert_from_bytes`.

**Comment by dougsouza** [comment] 2018-11-20 17:22
@Belval, I figured this is on the pdftoppm side, I am already investigating.

When a run pdftoppm I get: Bogus memory allocation size

The output is a 1x1 blank image.

Thanks for the help

**Comment by dougsouza** [comment] 2018-11-20 18:17
@Belval,

Just to share the solution: the mediaBox of my pdf was huge and it was eating up all the memory available rendering a lot of blank space. Turns out that the cropBox of the pdf was correct, so converting using the cropBox (`pdftoppm -cropbox ...`) works fine.

It would be nice to have an option to use the crop box instead, like:

`convert_from_path(..., use_crop_box=False)`

Cheers

**Comment by Belval** [comment] 2018-11-20 20:33
Can you try with https://github.com/Belval/pdf2image/tree/support-cropbox and see if it fixes your issue?

I will upload the new package to PyPi tonight if it does.

**Comment by dougsouza** [comment] 2018-11-20 20:45
I just tested. It works fine.

Thanks!!

**Comment by Belval** [comment] 2018-11-20 21:14
Pull request created: https://github.com/Belval/pdf2image/pull/35

Package uploaded: https://pypi.org/project/pdf2image/

Be aware that PyPi caches packages so it can take a few minutes until it is available.

**Comment by Belval** [comment] 2018-12-26 17:35
As this was fixed in a previous version, I am closing it.

**Closed by Belval** 2018-12-26 17:35 UTC

**Comment by alvercau** [comment] 2020-06-17 13:21
Hi

I've run into the same issue. Running with pdftoppm, without the wrapper, does not have the same issue, the jpeg gets correctly generated. 
Example file is attached.
[5ccad715074ce2b850f646d5-e70d52df-5671-4c97-bfcf-f7e20f5a61d6-1-MN5PADLAME2TMP2HM3JPETQQ33P7NDSQ.pdf](https://github.com/Belval/pdf2image/files/4792714/5ccad715074ce2b850f646d5-e70d52df-5671-4c97-bfcf-f7e20f5a61d6-1-MN5PADLAME2TMP2HM3JPETQQ33P7NDSQ.pdf)

**Comment by Belval** [comment] 2020-06-17 13:43
I was unable to reproduce the issue described with the linked file. Using pdftoppm version 0.62.0 the output image seems to correspond to the PDF.

Here is my code snippet:

```py
from pdf2image import convert_from_path
convert_from_path("test.pdf", size=(3000,))[0].save("out.png")
```

I changed the name of your PDF for reading purposes, I set a size to avoid the Pillow decompression bomb check.

Could you provide your pdftoppm version with `pdftoppm -v`and your function call?

**Comment by alvercau** [comment] 2020-06-17 13:48
Hi, I didn't set any size, so the issue is indeed that the image is too big. Would it be possible to have convert_from_path raise an error, explaining that the size is too big and that it can be avoided by setting the size parameter, instead of simply silently returning a white pixel?

**Comment by Belval** [comment] 2020-06-17 13:54
That's the thing, the underlying library that parses the image file should and does raise an exception on the PDF you linked:

```py
>>> from pdf2image import convert_from_path
>>> convert_from_path("test.pdf")[0].save("out.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 202, in convert_from_path
    images += parse_buffer_func(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pdf2image/parsers.py", line 21, in parse_buffer_to_ppm
    images.append(Image.open(BytesIO(data[index : index + file_size])))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/PIL/Image.py", line 2881, in open
    im = _open_core(fp, filename, prefix)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/PIL/Image.py", line 2868, in _open_core
    _decompression_bomb_check(im.size)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/PIL/Image.py", line 2793, in _decompression_bomb_check
    "could be decompression bomb DOS attack." % (pixels, 2 * MAX_IMAGE_PIXELS)
PIL.Image.DecompressionBombError: Image size (382369975 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

Do you override de Pillow limit somewhere else in your code?

**Comment by alvercau** [comment] 2020-06-17 14:03
The issue is not that pdf2image returns an image that is too big, but that it returns one single white pixel, without any warnings. 
`assert convert_from_path("test.pdf")[0].shape == (1,1)`
does not give any errors, as the shape of the image is 1.
If I convert the pdf to jpeg by means of the command line tool pdftoppm, the image gets correctly generated, and I do get the DecompressionBomb error when trying to open it with PIL. So the issue is in pdf2image, not in pdftoppm or PIL.

**Comment by Belval** [comment] 2020-06-17 14:30
I understand that, but I am simply to reproduce the issue, if I disable Pillow's warning, the saved image is correctly rendered.

In other word, I am unable to get the 1x1 white pixel output you describe.

**Comment by mananshah1403** [comment] 2022-02-09 20:42
@Belval I am still encountering this issue with the following PDF. please help!
[fail3.pdf](https://github.com/Belval/pdf2image/files/8036047/fail3.pdf)

**Comment by asanaa8** [comment] 2023-04-27 23:23
same issue here, Help.

**Comment by hedes1992** [comment] 2024-10-30 07:02
> @Belval,
> 
> Just to share the solution: the mediaBox of my pdf was huge and it was eating up all the memory available rendering a lot of blank space. Turns out that the cropBox of the pdf was correct, so converting using the cropBox (`pdftoppm -cropbox ...`) works fine.
> 
> It would be nice to have an option to use the crop box instead, like:
> 
> `convert_from_path(..., use_crop_box=False)`
> 
> Cheers

seems use_cropbox=False, refer to https://pdf2image.readthedocs.io/en/latest/reference.html
